local combat = Combat()
combat:setParameter(COMBAT_PARAM_BLOCKARMOR, true)
combat:setParameter(COMBAT_PARAM_TYPE, COMBAT_PHYSICALDAMAGE)
combat:setParameter(COMBAT_PARAM_DISTANCEEFFECT, 27)
combat:setParameter(COMBAT_PARAM_EFFECT, CONST_ME_ICEATTACK)
combat:setFormula(COMBAT_FORMULA_SKILL, 1.5, -30, 2.0, -100)

local condition = Condition(CONDITION_FREEZING)
condition:setParameter(CONDITION_PARAM_DELAYED, true)
condition:addDamage(1, 2000, -73)
condition:addDamage(1, 2000, -72)
condition:addDamage(1, 2000, -54)
condition:addDamage(1, 2000, -31)
condition:addDamage(1, 2000, -27)
condition:addDamage(1, 2000, -23)
condition:addDamage(1, 2000, -11)
condition:addDamage(1, 2000, -11)
condition:addDamage(1, 2000, -1)
condition:addDamage(1, 2000, -1)
condition:addDamage(1, 2000, -1)
combat:addCondition(condition)

local crystalArrow = Weapon(WEAPON_AMMO)

function crystalArrow.onUseWeapon(player, variant)
	return combat:execute(player, variant)
end
crystalArrow:id(3239)
crystalArrow:attack(111)
crystalArrow:ammoType("arrow")
crystalArrow:shootType(CONST_ME_ICEATTACK)
crystalArrow:register()
