local combat = Combat()
combat:setParameter(COMBAT_PARAM_BLOCKARMOR, true)
combat:setParameter(COMBAT_PARAM_BLOCKSHIELD, true)
combat:setParameter(COMBAT_PARAM_TYPE, COMBAT_PHYSICALDAMAGE)
combat:setParameter(COMBAT_PARAM_EFFECT, CONST_ME_SMALLPLANTS)
combat:setFormula(COMBAT_FORMULA_SKILL, 0.2, 30, 1.2, -180)

local condition = Condition(CONDITION_POISON)
condition:setParameter(CONDITION_PARAM_DELAYED, 1)
condition:addDamage(1, 2000, -73)
condition:addDamage(1, 2000, -72)
condition:addDamage(1, 2000, -54)
condition:addDamage(1, 2000, -31)
condition:addDamage(1, 2000, -27)
condition:addDamage(1, 2000, -23)
condition:addDamage(1, 2000, -11)
condition:addDamage(1, 2000, -11)
condition:addDamage(1, 2000, -1)
condition:addDamage(1, 2000, -1)
condition:addDamage(1, 2000, -1)
combat:addCondition(condition)

local trynity = Weapon(WEAPON_CLUB)
trynity.onUseWeapon = function(player, variant)
	return combat:execute(player, variant)
end
trynity:id(8809)
--starwand:shootType(CONST_ANI_HOLY)
trynity:register()
