local combat = createCombatObject()
setCombatParam(combat, COMBAT_PARAM_BLOCKARMOR, 1)
setCombatParam(combat, COMBAT_PARAM_TYPE, COMBAT_PHYSICALDAMAGE)
setCombatParam(combat, COMBAT_PARAM_DISTANCEEFFECT, 27)
setCombatParam(combat, COMBAT_PARAM_EFFECT, CONST_ME_ICEATTACK)
setCombatFormula(combat, COMBAT_FORMULA_SKILL, 1.5, -30, 2.0, -100)

local condition = createConditionObject(CONDITION_FREEZING)
setConditionParam(condition, CONDITION_PARAM_DELAYED, 1)
addDamageCondition(condition, 1, 2000, -73)
addDamageCondition(condition, 1, 2000, -72)
addDamageCondition(condition, 1, 2000, -54)
addDamageCondition(condition, 1, 2000, -31)
addDamageCondition(condition, 1, 2000, -27)
addDamageCondition(condition, 1, 2000, -23)
addDamageCondition(condition, 1, 2000, -11)
addDamageCondition(condition, 1, 2000, -11)
addDamageCondition(condition, 1, 2000, -1)
addDamageCondition(condition, 1, 2000, -1)
addDamageCondition(condition, 1, 2000, -1)
setCombatCondition(combat, condition)

function onUseWeapon(cid, var)
	return doCombat(cid, combat, var)
end
