local combat = createCombatObject()
setCombatParam(combat, COMBAT_PARAM_BLOCKARMOR, 2)
setCombatParam(combat, COMBAT_PARAM_BLOCKSHIELD, 2)
setCombatParam(combat, COMBAT_PARAM_TYPE, COMBAT_PHYSICALDAMAGE)
setCombatParam(combat, COMBAT_PARAM_EFFECT, CONST_ME_ENERGYHIT)
setCombatFormula(combat, COMBAT_FORMULA_SKILL, 0.2, 30, 1.2, -180)

local condition = createConditionObject(CONDITION_ENERGY)
setConditionParam(condition, CONDITION_PARAM_DELAYED, 1)
addDamageCondition(condition, 1, 2000, -73)
addDamageCondition(condition, 1, 2000, -72)
addDamageCondition(condition, 1, 2000, -54)
addDamageCondition(condition, 1, 2000, -31)
addDamageCondition(condition, 1, 2000, -27)
addDamageCondition(condition, 1, 2000, -23)
addDamageCondition(condition, 1, 2000, -11)
addDamageCondition(condition, 1, 2000, -11)
addDamageCondition(condition, 1, 2000, -1)
addDamageCondition(condition, 1, 2000, -1)
addDamageCondition(condition, 1, 2000, -1)
setCombatCondition(combat, condition)

local excalibur = Weapon(WEAPON_SWORD)
excalibur.onUseWeapon = function(player, variant)
	return combat:execute(player, variant)
end
excalibur:id(8980)
--starwand:shootType(CONST_ANI_HOLY)
excalibur:register()
